version: '3'
services:
  php:
    image: its404/alpine-php7.2-nginx
    volumes:
      - ./:/var/www
      - ~/.docker-composer/cache:/root/.composer/cache
    ports:
      - '8000:80'
    environment:
      PHP_XDEBUG_REMOTE_HOST: docker.for.mac.localhost
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: app
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
volumes:
    db-data: